SPK_NAME = qbittorrent-enhanced
SPK_VERS = 4.6.5.10
SPK_REV = 1
SPK_ICON = src/qbittorrent-enhanced.png
BETA = 1

DEPENDS = cross/qbittorrent-enhanced

MAINTAINER = kdiy7396
DISPLAY_NAME = qBittorrent Enhanced
DESCRIPTION = Advanced qBittorrent Enhanced Edition with default admin/admin
CHANGELOG = "Initial GitHub Actions build"
LICENSE = GPLv2
STARTABLE = yes
SERVICE_USER = auto
SERVICE_SETUP = src/service-setup

include ../../mk/spksrc.spk.mk
